Show an error messager for invalid semver spec for packages in the [replace] section.
The [replace] section in the Cargo.toml file doesn't allow invalid semver specs
for packages, so something like this:

    [dependencies]
    foo = "*"

    [replace]
    "foo:*" = { git = 'https://example.com' }

It's not valid. In this case we will display an error message like this:

    error: failed to parse manifest at `Cargo.toml`

    Caused by:
      replacements must specify a valid semver version to replace, but `foo:*` does not